## Question 1:Create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays

In [1]:
import numpy as np
x = np.array([1, 2])
y = np.array([3, 4])
print("Original numbers:")
print(x)
print(y)
print("Comparison - greater")
print(np.greater(x, y))
print("Comparison - greater_equal")
print(np.greater_equal(x, y))
print("Comparison - less")
print(np.less(x, y))
print("Comparison - less_equal")
print(np.less_equal(x, y))

Original numbers:
[1 2]
[3 4]
Comparison - greater
[False False]
Comparison - greater_equal
[False False]
Comparison - less
[ True  True]
Comparison - less_equal
[ True  True]


## Question 2:Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives

In [2]:
array = np.zeros(10)
print("The 10 zeors array ")
print(array)
array = np.ones(10)
print("The 10 ones array ")
print(array)
array = np.ones(10)*5
print("The 10 fives ")
print(array)

The 10 zeors array 
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
The 10 ones array 
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
The 10 fives 
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


### Question 3:Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of agiven array

In [3]:
x = np.array([[1,2,4],
                 [3,5,7]])
print("The original array ")
print(x)
print("The sum of total element")
print(np.sum(x))
print("The sum of all columns")
print(np.sum(x,axis=0))
print("The sum of all rows")
print(np.sum(x,axis=1))

The original array 
[[1 2 4]
 [3 5 7]]
The sum of total element
22
The sum of all columns
[ 4  7 11]
The sum of all rows
[ 7 15]


### Question 4:​Write a NumPy program to add, subtract, multiply, divide arguments element-wise.

In [4]:
x = np.array([[2,5]])
y = np.array([[4,6]])
print("The original value of x")
print(x)
print("The original value of y")
print(y)
print("The elementswise Additin of the two arrays")
print(np.add(x,y))
print("The elements subtraction of the two arrays")
print(np.subtract(x,y))
print("The elements Multiplication of the two arrays")
print(np.multiply(x,y))
print("The elements Divided of the two arrays")
print(np.divide(x,y))

The original value of x
[[2 5]]
The original value of y
[[4 6]]
The elementswise Additin of the two arrays
[[ 6 11]]
The elements subtraction of the two arrays
[[-2 -1]]
The elements Multiplication of the two arrays
[[ 8 30]]
The elements Divided of the two arrays
[[0.5        0.83333333]]


In [5]:
x

array([[2, 5]])

### Question 5:Write a NumPy program to compute the trigonometric sine, cosine and tangent array of angles given indegree.

In [6]:
print("The Trigonometric sine")
print(np.sin(np.array((0., 30., 45., 60., 90.))*np.pi/180))
print("The Trigonometric consine")
print(np.cos(np.array((0., 30., 45., 60., 90.))*np.pi/180))
print("The Trigonometric tangent")
print(np.tan(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))

The Trigonometric sine
[0.         0.5        0.70710678 0.8660254  1.        ]
The Trigonometric consine
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
The Trigonometric tangent
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


### Question 6:Write a Pandas program to create and display a DataFrame from a specified dictionary data which has theindex labels

In [7]:
import pandas as pd
exam_data  = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data , index=labels)

df.head()

name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no

### Question 7:Write a Pandas program to select the 'name' and 'score' columns from the following DataFrame.

In [8]:
print("Select specific columns:")
print(df[['name', 'score']])

Select specific columns:
        name  score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine   16.5
d      James    NaN
e      Emily    9.0
f    Michael   20.0
g    Matthew   14.5
h      Laura    NaN
i      Kevin    8.0
j      Jonas   19.0


### Question 8:Write a Pandas program to join the two given dataframes along rows and assign all datav

In [9]:
student_data1 = pd.DataFrame({
        'student_id': ['S1', 'S2', 'S3', 'S4', 'S5'],
         'name': ['Danniella Fenton', 'Ryder Storey', 'Bryce Jensen', 'Ed Bernal', 'Kwame Morin'], 
        'marks': [200, 210, 190, 222, 199]})

student_data2 = pd.DataFrame({
        'student_id': ['S4', 'S5', 'S6', 'S7', 'S8'],
        'name': ['Scarlette Fisher', 'Carla Williamson', 'Dante Morse', 'Kaiser William', 'Madeeha Preston'], 
        'marks': [201, 200, 198, 219, 201]})

print("Original DataFrames:")
print(student_data1)
print("-------------------------------------")
print(student_data2)
print("\nJoin the said two dataframes along rows:")
result_data = pd.concat([student_data1, student_data2],ignore_index=True)
print(result_data)

Original DataFrames:
  student_id              name  marks
0         S1  Danniella Fenton    200
1         S2      Ryder Storey    210
2         S3      Bryce Jensen    190
3         S4         Ed Bernal    222
4         S5       Kwame Morin    199
-------------------------------------
  student_id              name  marks
0         S4  Scarlette Fisher    201
1         S5  Carla Williamson    200
2         S6       Dante Morse    198
3         S7    Kaiser William    219
4         S8   Madeeha Preston    201

Join the said two dataframes along rows:
  student_id              name  marks
0         S1  Danniella Fenton    200
1         S2      Ryder Storey    210
2         S3      Bryce Jensen    190
3         S4         Ed Bernal    222
4         S5       Kwame Morin    199
5         S4  Scarlette Fisher    201
6         S5  Carla Williamson    200
7         S6       Dante Morse    198
8         S7    Kaiser William    219
9         S8   Madeeha Preston    201


In [10]:
frames = [student_data1,student_data2]
df_keys = pd.concat(frames, keys=['x', 'y'])

df_keys

student_id              name  marks
x 0         S1  Danniella Fenton    200
  1         S2      Ryder Storey    210
  2         S3      Bryce Jensen    190
  3         S4         Ed Bernal    222
  4         S5       Kwame Morin    199
y 0         S4  Scarlette Fisher    201
  1         S5  Carla Williamson    200
  2         S6       Dante Morse    198
  3         S7    Kaiser William    219
  4         S8   Madeeha Preston    201

In [11]:
frames = {'x':student_data1,'y':student_data2}
df_keys = pd.concat(frames)
print(df_keys)

    student_id              name  marks
x 0         S1  Danniella Fenton    200
  1         S2      Ryder Storey    210
  2         S3      Bryce Jensen    190
  3         S4         Ed Bernal    222
  4         S5       Kwame Morin    199
y 0         S4  Scarlette Fisher    201
  1         S5  Carla Williamson    200
  2         S6       Dante Morse    198
  3         S7    Kaiser William    219
  4         S8   Madeeha Preston    201


### Question 9:Write a Pandas program to detect missing values of a given DataFrame. Display True or False.

In [12]:
exam_data  = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
df = pd.DataFrame(exam_data)

In [13]:
df.isna()

name  score  attempts  qualify
0  False  False     False    False
1  False  False     False    False
2  False  False     False    False
3  False   True     False    False
4  False  False     False    False
5  False  False     False    False
6  False  False     False    False
7  False   True     False    False
8  False  False     False    False
9  False  False     False    False

### Question 10: Write a Pandas program to create and display a one-dimensional array-like object containing an array ofdata

In [14]:
x = pd.Series([1,3,5,6,7],index=['p','q','r','s','t'])
print(x)

p    1
q    3
r    5
s    6
t    7
dtype: int64
